### PR TITLE
iteritems fix for python 3

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by wpoely86** [comment]
@boegel have a look

**Comment by boegel** [comment]
Also, can we make the tests trip over this?

**Comment by boegel** [comment]
@wpoely86 ping on this?

**Comment by wpoely86** [comment]
I switched to using `items()` and make some changes to make the linter happy.

This module has no tests to speak of so you have to start from scratch. I'm not sure if I can find the time for that in the near future...

**Comment by stdweird** [comment]
@wpoely86 can you rerun `python -m vsc.install.ci` and push?

**Pull request merged**
